name: event_db
description: A companion package for handling models and databases using the event bloc.
version: 0.1.19
repository: https://github.com/VHCBlade/event_db

environment:
  sdk: '>=2.19.2 <4.0.0'

dependencies:
  collection: ^1.17.0
  
  event_bloc: ^4.2.0
  flutter:
    sdk: flutter

  test: ^1.21.0
  tuple: ^2.0.0
  uuid: ^3.0.7

dev_dependencies:
  event_bloc_tester: ^0.1.4

  flutter_test:
    sdk: flutter

  very_good_analysis: ^5.0.0

flutter:
