name: event_db
description: A companion package for handling models and databases using the event bloc.
version: 0.1.4
repository: https://github.com/VHCBlade/event_db

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  event_bloc: ^4.2.0
  tuple: ^2.0.0
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  lints: ^2.0.0
  test: ^1.21.0

flutter:
