name: flutter_bloc_library
description: A starting point for Dart libraries or applications.
version: 1.1.0
homepage: https://github.com/VHCBlade/flutter_bloc_library/commit/5079994e794621a6a2821d21c5416d4d47658472
# author: Vincent Haron <VHCBlade@gmail.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
  rxdart: ^0.22.0
  equatable: ^0.2.5
